---

- name: Install php and apache
  apt:
    name: php
    state: present

- name: Install php extensions
  apt:
    name: "{{ php_extensions }}"
    state: present

- name: Check if composer is installed
  shell: type composer >/dev/null 2>&1
  register: composer_result
  ignore_errors: yes

- name: Install composer
  shell: |
    curl -sS https://getcomposer.org/installer -o composer-setup.php \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php
  when: composer_result.stdout.find('not found') != -1

