---

- name: Install commonly used packages
  become: true
  apt:
    update_cache: yes
    name:
      - software-properties-common
      - build-essential
      - htop
      - vim
      - curl
      - net-tools
      - unzip
    state: present

- name: Copy shell script
  template:
    src: set-working-dir.sh
    dest: "{{ project_dir }}/"
    mode: 0744

- name: Set working directory to project root directory on vagrant ssh
  shell: "{{ project_dir }}/set-working-dir.sh"

- name: Remove shell script
  file:
    path: "{{ project_dir }}/set-working-dir.sh"
    state: absent
