---

project_dir: /var/default-project-name

common_packages:
  - software-properties-common
  - build-essential
  - htop
  - vim
  - curl
  - net-tools
  - unzip

php_extensions:
  - php-xdebug
  - php-curl
  - php-xml
  - php-soap
  - php-bcmath
  - php-mbstring
  - php-apcu
  - php-memcached
  - php-mysqli
